ARG RUBY_VERSION
FROM ruby:${RUBY_VERSION}-alpine

ARG BUNDLER_VERSION

ENV LANG=C.UTF-8
ENV APP_PATH /app
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3000

ENV BUNDLE_JOBS 20
ENV BUNDLE_RETRY 5

RUN apk -U add --no-cache \
  build-base \
  git \
  postgresql-dev \
  postgresql-client \
  libxml2-dev \
  libxslt-dev \
  nodejs \
  yarn \
  imagemagick \
  tzdata \
  less \
  && rm -rf /var/cache/apk/* \
  && mkdir -p "$APP_PATH"

RUN gem update --system \
  && gem install bundler --version "$BUNDLER_VERSION" \
  && rm -rf "$GEM_HOME/cache/*"

WORKDIR $APP_PATH

EXPOSE $RAILS_PORT
