name: Main
on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  FILBUNKE_NODE_VERSION_SPEC: '16'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.FILBUNKE_NODE_VERSION_SPEC }}
          cache: yarn
      - name: Install Node packages
        run: yarn install --immutable

      - name: Rubocop
        run: bundle exec rubocop --parallel
      - name: ESLint
        run: yarn lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgresql://filbunke:filbunke@localhost:5432/filbunke_test'
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: filbunke
          POSTGRES_PASSWORD: filbunke
          POSTGRES_DB: filbunke_test
        ports: ['5432:5432']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.FILBUNKE_NODE_VERSION_SPEC }}
          cache: yarn
      - name: Install Node packages
        run: yarn install --immutable

      - name: Prepare test database
        run: bundle exec rails db:prepare

      - name: Run tests
        run: bundle exec rake test
